// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

export const SUPABASE_URL = "https://edmpqigdqdugrvxpqrau.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVkbXBxaWdkcWR1Z3J2eHBxcmF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0MTcxOTcsImV4cCI6MjA2Nzk5MzE5N30.Le7nIo-UFMzjkFVjNEMyI0Wt8rOoIK0Xfo6Uftu4y_E";

// Make Supabase URL available globally for Edge Function calls
if (typeof window !== 'undefined') {
  (window as any).VITE_SUPABASE_URL = SUPABASE_URL;
}

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error('Missing Supabase environment variables');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce',
    debug: false,
  },
});